#!/usr/bin/env node
// index.html 의 목적지 데이터를 읽어 노선별 정적 페이지를 생성한다.
//
//   node tools/build-pages.js          생성 (파일 기록)
//   node tools/build-pages.js --check  생성 결과가 저장소와 같은지만 확인
//
// 왜 정적 파일로 만드는가
//   검색엔진은 자바스크립트로 뽑히는 목적지를 색인할 수 없다. "서울에서 강릉 가는
//   고속버스" 같은 검색어로 유입되려면 목적지마다 실제 HTML 문서가 있어야 한다.
//
// 왜 빌드 결과를 저장소에 커밋하는가
//   netlify.toml 에 빌드 명령이 없다(publish = "."). 이 상태를 유지하면 배포가
//   단순히 파일 복사라서 실패할 여지가 없다. 대신 생성물이 데이터와 어긋나면
//   tests/pages.test.js 가 잡는다.
//
// 데이터는 index.html 한 곳에만 둔다. 여기서는 읽기만 하고, 페이지에 필요한
// 값은 각 페이지의 <script> 에 그 목적지 것만 인라인으로 박아 넣는다
// (별도 데이터 파일을 두면 둘이 어긋날 여지가 생긴다).
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SITE = 'https://randomtago.netlify.app';
const DIR = '노선';                    // 생성 페이지가 들어갈 상위 폴더
const MARK = '<!-- generated by tools/build-pages.js — 직접 고치지 마세요 -->';

// ── index.html 에서 선언 하나를 그대로 떼어내 평가한다 ──
// 정규식으로 중첩 배열을 파싱하면 금방 깨진다. 괄호 깊이를 세어 초기화식의
// 끝을 찾고 그 표현식만 평가한다(문자열 안의 괄호·주석은 건너뛴다).
function declSource(src, name) {
  const at = src.indexOf(`const ${name} = `);
  if (at < 0) throw new Error(`index.html 에서 ${name} 선언을 찾지 못했습니다`);
  let i = src.indexOf('=', at) + 1;
  while (/\s/.test(src[i])) i++;
  const start = i;
  let depth = 0, quote = null;
  for (; i < src.length; i++) {
    const c = src[i];
    if (quote) {
      if (c === '\\') i++;
      else if (c === quote) quote = null;
      continue;
    }
    if (c === '"' || c === "'" || c === '`') { quote = c; continue; }
    if (c === '/' && src[i + 1] === '/') { i = src.indexOf('\n', i); continue; }
    if (c === '[' || c === '{' || c === '(') depth++;
    else if (c === ']' || c === '}' || c === ')') depth--;
    else if (c === ';' && depth === 0) return src.slice(start, i);
  }
  throw new Error(`${name} 선언의 끝을 찾지 못했습니다`);
}

const evalDecl = (src, name) => new Function(`return (${declSource(src, name)})`)();

// ── 문자열 도구 ──
const esc = s => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;');

// 한글 종성 유무로 조사를 고른다. "강릉은 / 속초는" 을 손으로 맞추면 반드시 틀린다.
function hasJong(w) {
  const c = w.charCodeAt(w.length - 1);
  if (c < 0xac00 || c > 0xd7a3) return true;      // 한글이 아니면 있는 쪽으로
  return (c - 0xac00) % 28 !== 0;
}
const josa = (w, pair) => { const [a, b] = pair.split('/'); return w + (hasJong(w) ? a : b); };

const won = n => n.toLocaleString('ko-KR') + '원';
const durText = m => {
  const h = Math.floor(m / 60), mm = m % 60;
  return [h ? h + '시간' : '', mm ? mm + '분' : ''].filter(Boolean).join(' ') || '0분';
};
const slug = n => n.replace(/·/g, '-');
const mapUrl = q => 'https://map.naver.com/p/search/' + encodeURIComponent(q);

// 출발지 표기. 호남선은 같은 단지 안이지만 건물 이름이 센트럴시티라
// "서울고속버스터미널 호남선" 이라고 쓰면 현장에서 헷갈린다.
const DEPART = { gb: '서울고속버스터미널(경부·영동선)', hn: '센트럴시티터미널(호남선)' };

// ── 데이터 읽기 ──
function load() {
  const src = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  const d = {};
  for (const name of ['DEST', 'TERM_LABEL', 'REGION_CODE', 'REGION_VIBE', 'SPOTS',
    'COORD', 'DEP_ID', 'DEP_HINT', 'TAGO_ARR_ID', 'TAGO_ARR', 'SEASIDE', 'SEARCH_CITY']) {
    d[name] = evalDecl(src, name);
  }
  return d;
}

// ── 페이지 조각 ──
function head({ title, desc, url, extraLd }) {
  return `<!DOCTYPE html>
<html lang="ko">
<head>
${MARK}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(title)}</title>
<meta name="description" content="${esc(desc)}">
<link rel="canonical" href="${encodeURI(url)}">
<meta name="theme-color" content="#0c0f16">
<meta property="og:type" content="article">
<meta property="og:url" content="${encodeURI(url)}">
<meta property="og:site_name" content="오늘의 랜덤 여행">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(desc)}">
<meta property="og:image" content="${SITE}/og.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🚌</text></svg>">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Gothic+A1:wght@400;500;700;900&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/assets/dest.css">
<script type="application/ld+json">${JSON.stringify(extraLd)}</script>
</head>
<body>`;
}

const siteHeader = `<header class="top">
  <a class="brand" href="/">🚌 오늘의 랜덤 여행</a>
  <nav><a href="/${DIR}/">노선 전체</a></nav>
</header>`;

const siteFooter = `<footer class="foot">
  <p>요금·소요시간은 우등 기준 편도 예상값이며 날짜와 좌석 등급에 따라 달라집니다.
  실제 출발편과 잔여석은 <a href="https://www.kobus.co.kr" target="_blank" rel="noopener">코버스</a>에서 확인하세요.</p>
  <p>배차 정보는 <a href="https://www.data.go.kr" target="_blank" rel="noopener">공공데이터포털</a> 전국고속버스 API,
  날씨는 <a href="https://open-meteo.com" target="_blank" rel="noopener">Open-Meteo</a> 자료입니다.</p>
</footer>`;

// 목적지 소개 문단. 요금·소요시간을 문장으로 한 번 더 풀어 준다
// (표만 있으면 검색 결과에 쓸 만한 문장이 없다).
function intro(d, D) {
  const n = d.n, s = [];
  s.push(`${DEPART[d.t]}에서 ${n}까지는 ${d.grade} 기준 편도 ${won(d.fare)},`
    + ` 약 ${durText(d.dur)} 걸립니다.`);
  if (d.dur <= 150) s.push(`${josa(n, '은/는')} 당일치기로 다녀오기 좋은 거리입니다.`);
  else if (d.dur <= 210) s.push('아침 일찍 나서면 당일치기도 되지만, 여유 있게 보려면 1박이 편합니다.');
  else s.push(`편도만 ${durText(d.dur)}이라 1박 일정을 권합니다.`);
  if (D.SEASIDE.has(n)) s.push('바다를 끼고 있어 해안 산책이나 회 한 상 코스를 넣기 좋습니다.');
  else s.push(`${D.REGION_VIBE[d.r]}으로 묶이는 ${d.r} 권역입니다.`);
  return s.join(' ');
}

function factList(d, D) {
  const daytrip = d.dur <= 150 ? '당일치기 좋아요'
    : d.dur <= 210 ? '부지런하면 당일치기' : '1박 추천';
  const rows = [
    ['출발', DEPART[d.t]],
    ['도착', d.n],
    ['예상 요금', `${won(d.fare)} <small>/ ${esc(d.grade)}</small>`],
    ['소요시간', durText(d.dur)],
    ['권역', `${esc(d.r)} · ${esc(D.REGION_VIBE[d.r] || '')}`],
    ['일정', daytrip],
  ];
  return `<dl class="facts">`
    + rows.map(([k, v]) => `<div><dt>${esc(k)}</dt><dd>${v}</dd></div>`).join('')
    + `</dl>`;
}

// 볼거리 데이터가 없으면 지도 검색 바로가기로 채운다(index.html 과 같은 방식).
const FALLBACK = [['관광지', '가볼 만한 곳 둘러보기'], ['맛집', '현지 밥집 찾기'],
  ['카페', '쉬어 갈 곳'], ['전통시장', '장 구경']];

function spotsSection(d, D) {
  const city = D.SEARCH_CITY[d.n] || d.n.split('·')[0];
  const items = (D.SPOTS[d.n] && D.SPOTS[d.n].length)
    ? D.SPOTS[d.n]
    : FALLBACK.map(([k, desc]) => [city + ' ' + k, desc, '검색']);
  const q = name => (name.includes(city) ? name : city + ' ' + name);
  const cards = items.map(([name, desc, tag]) => `<li>
      <a href="${esc(mapUrl(q(name)))}" target="_blank" rel="noopener">
        <div class="sn">${esc(name)}<span class="tag">${esc(tag)}</span></div>
        <div class="sd">${esc(desc)}</div>
      </a></li>`).join('\n');
  return `<section class="block">
  <h2>${esc(d.n)} 근처 볼거리</h2>
  <ul class="spots">
${cards}
  </ul>
  <p class="more"><a href="${esc(mapUrl(city + ' 관광지'))}" target="_blank" rel="noopener">${esc(city)} 관광지 지도에서 더 보기 →</a></p>
</section>`;
}

function nearbySection(d, all) {
  const same = all.filter(x => x.r === d.r && x.n !== d.n)
    .sort((a, b) => a.fare - b.fare).slice(0, 12);
  if (!same.length) return '';
  const links = same.map(x =>
    `<li><a href="/${DIR}/${encodeURIComponent(slug(x.n))}/"><b>${esc(x.n)}</b><span>${won(x.fare)} · ${durText(x.dur)}</span></a></li>`
  ).join('\n');
  return `<section class="block">
  <h2>같은 권역 다른 목적지</h2>
  <ul class="links">
${links}
  </ul>
</section>`;
}

// ── 목적지 페이지 ──
function destPage(d, D, all) {
  const url = `${SITE}/${DIR}/${slug(d.n)}/`;
  const spots = (D.SPOTS[d.n] || []).map(s => s[0]);
  const title = `서울에서 ${d.n} 가는 고속버스 — 요금·소요시간·볼거리`;
  const desc = `${DEPART[d.t]}에서 ${d.n}까지 ${d.grade} ${won(d.fare)}, 약 ${durText(d.dur)}.`
    + (spots.length ? ` 오늘 배차와 날씨, ${spots.slice(0, 2).join(', ')} 같은 근처 볼거리를 정리했습니다.`
      : ' 오늘 배차와 날씨, 근처 볼거리를 정리했습니다.');

  const ld = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: '오늘의 랜덤 여행', item: SITE + '/' },
      { '@type': 'ListItem', position: 2, name: '노선 전체', item: encodeURI(`${SITE}/${DIR}/`) },
      { '@type': 'ListItem', position: 3, name: `서울 → ${d.n}` },
    ],
  };

  // 페이지 스크립트에 필요한 값만 인라인으로 넘긴다
  const c = D.COORD[d.n] || [];
  const page = {
    n: d.n, t: d.t, dur: d.dur, sea: D.SEASIDE.has(d.n),
    lat: c[0], lon: c[1],
    arr: D.TAGO_ARR[d.n] || d.n.split('·')[0],
    arrId: D.TAGO_ARR_ID[d.n] || null,
    depId: D.DEP_ID[d.t] || null,
    depHint: D.DEP_HINT[d.t] || '서울경부',
  };

  return `${head({ title, desc, url, extraLd: ld })}
${siteHeader}
<main>
  <p class="crumb"><a href="/">홈</a> › <a href="/${DIR}/">노선</a> › 서울 → ${esc(d.n)}</p>
  <h1>서울에서 ${esc(d.n)} 가는 고속버스</h1>
  <p class="lead">${esc(intro(d, D))}</p>
  ${factList(d, D)}

  <section class="block">
    <h2>오늘 배차와 요금</h2>
    <div id="live" class="live loading">실제 배차 정보를 불러오는 중…</div>
    <p class="hint">전국고속버스 API 는 오늘과 내일 배차만 제공합니다. 그 이후 날짜는 코버스에서 확인하세요.</p>
  </section>

  <section class="block">
    <h2>${esc(d.n)} 날씨</h2>
    <div id="weather" class="weather loading">날씨를 불러오는 중…</div>
  </section>

${spotsSection(d, D)}

  <section class="cta">
    <a class="btn primary" href="/?to=${encodeURIComponent(d.n)}">${esc(d.n)} 승차권 보기</a>
    <a class="btn" href="/">목적지 랜덤으로 뽑기</a>
  </section>

${nearbySection(d, all)}
</main>
${siteFooter}
<script>window.RT_PAGE=${JSON.stringify(page)};</script>
<script src="/assets/dest.js" defer></script>
</body>
</html>
`;
}

// ── 노선 목록(허브) 페이지 ──
// 이 페이지가 없으면 99개 페이지가 홈에서 닿지 않는 고아 문서가 된다.
function hubPage(D, all) {
  const url = `${SITE}/${DIR}/`;
  const title = `서울고속버스터미널 출발 노선 ${all.length}곳 — 요금·소요시간 한눈에`;
  const desc = `서울고속버스터미널(경부·영동선)과 센트럴시티(호남선)에서 갈 수 있는 ${all.length}곳의`
    + ` 편도 요금과 소요시간을 권역별로 정리했습니다.`;
  const regions = [...new Set(all.map(d => d.r))];
  const ld = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: '오늘의 랜덤 여행', item: SITE + '/' },
      { '@type': 'ListItem', position: 2, name: '노선 전체' },
    ],
  };

  const sections = regions.map(r => {
    const list = all.filter(d => d.r === r).sort((a, b) => a.dur - b.dur);
    const rows = list.map(d => `<tr>
        <th scope="row"><a href="/${DIR}/${encodeURIComponent(slug(d.n))}/">${esc(d.n)}</a></th>
        <td>${won(d.fare)}</td><td>${durText(d.dur)}</td><td>${esc(D.TERM_LABEL[d.t])}</td></tr>`).join('\n');
    return `<section class="block">
  <h2>${esc(r)} <span class="vibe">${esc(D.REGION_VIBE[r] || '')} · ${list.length}곳</span></h2>
  <table class="grid">
    <thead><tr><th scope="col">목적지</th><th scope="col">요금</th><th scope="col">소요시간</th><th scope="col">출발 터미널</th></tr></thead>
    <tbody>
${rows}
    </tbody>
  </table>
</section>`;
  }).join('\n\n');

  return `${head({ title, desc, url, extraLd: ld })}
${siteHeader}
<main>
  <p class="crumb"><a href="/">홈</a> › 노선</p>
  <h1>서울 출발 고속버스 노선 ${all.length}곳</h1>
  <p class="lead">${esc(desc)} 목적지를 누르면 오늘 배차와 날씨, 근처 볼거리를 볼 수 있습니다.</p>

${sections}

  <section class="cta">
    <a class="btn primary" href="/">랜덤으로 목적지 뽑기</a>
  </section>
</main>
${siteFooter}
</body>
</html>
`;
}

function sitemap(all) {
  // lastmod 는 넣지 않는다. 빌드 시각을 쓰면 내용이 그대로인데도 매번 달라져
  // 생성물 비교 테스트가 의미를 잃는다.
  const urls = [`${SITE}/`, encodeURI(`${SITE}/${DIR}/`),
    ...all.map(d => encodeURI(`${SITE}/${DIR}/${slug(d.n)}/`))];
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url><loc>${u}</loc></url>`).join('\n')}
</urlset>
`;
}

const robots = () => `User-agent: *
Allow: /

Sitemap: ${SITE}/sitemap.xml
`;

// ── 전체 생성 ──
// 경로 → 내용 맵을 돌려준다. 기록은 호출한 쪽에서 한다(테스트는 비교만 한다).
function build() {
  const D = load();
  const all = D.DEST;
  const out = new Map();

  for (const d of all) out.set(`${DIR}/${slug(d.n)}/index.html`, destPage(d, D, all));
  out.set(`${DIR}/index.html`, hubPage(D, all));
  out.set('sitemap.xml', sitemap(all));
  out.set('robots.txt', robots());
  return { files: out, dest: all };
}

// 생성물이 아닌 파일을 지우지 않도록, 표식이 든 파일만 정리 대상으로 본다
function staleFiles(keep) {
  const dir = path.join(ROOT, DIR);
  if (!fs.existsSync(dir)) return [];
  const stale = [];
  const walk = rel => {
    for (const e of fs.readdirSync(path.join(ROOT, rel), { withFileTypes: true })) {
      const r = rel + '/' + e.name;
      if (e.isDirectory()) walk(r);
      else if (e.name === 'index.html' && !keep.has(r)
        && fs.readFileSync(path.join(ROOT, r), 'utf8').includes(MARK)) stale.push(r);
    }
  };
  walk(DIR);
  return stale;
}

function main() {
  const check = process.argv.includes('--check');
  const { files, dest } = build();

  if (check) {
    const diff = [];
    for (const [rel, body] of files) {
      let cur = null;
      try { cur = fs.readFileSync(path.join(ROOT, rel), 'utf8'); } catch { /* 없음 */ }
      if (cur !== body) diff.push(cur === null ? `없음: ${rel}` : `다름: ${rel}`);
    }
    staleFiles(new Set(files.keys())).forEach(r => diff.push(`남아 있음: ${r}`));
    if (diff.length) {
      console.error(`생성물이 index.html 과 어긋납니다 (${diff.length}건)`);
      diff.slice(0, 20).forEach(m => console.error('  ' + m));
      if (diff.length > 20) console.error(`  … 그 외 ${diff.length - 20}건`);
      console.error('\n  node tools/build-pages.js 를 실행한 뒤 함께 커밋하세요.');
      process.exit(1);
    }
    console.log(`생성물이 최신입니다 (${files.size}개 파일 / 목적지 ${dest.length}곳)`);
    return;
  }

  let wrote = 0;
  for (const [rel, body] of files) {
    const full = path.join(ROOT, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    let cur = null;
    try { cur = fs.readFileSync(full, 'utf8'); } catch { /* 새 파일 */ }
    if (cur !== body) { fs.writeFileSync(full, body); wrote++; }
  }

  const stale = staleFiles(new Set(files.keys()));
  for (const rel of stale) {
    fs.rmSync(path.join(ROOT, rel));
    const dir = path.dirname(path.join(ROOT, rel));
    if (!fs.readdirSync(dir).length) fs.rmdirSync(dir);
  }

  console.log(`목적지 ${dest.length}곳 · 파일 ${files.size}개 (변경 ${wrote}개, 삭제 ${stale.length}개)`);
  if (stale.length) stale.forEach(r => console.log('  삭제: ' + r));
}

if (require.main === module) main();
module.exports = { build, staleFiles, MARK, DIR, SITE, slug, ROOT };
